name: Markdown Lint

on:
  push:
    branches:
    - main
  pull_request:

jobs:
  build:
    name: Markdown Lint
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: nosborn/github-action-markdown-cli@v3.2.0
      with:
        files: "./**/*.md"
        config_file: .markdownlint.yaml
